additionalArguments:
  - "--accesslog=true"
  - "--accesslog.format=json"
  - "--log.level=DEBUG"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.entryPoint=metrics"
  - "--entryPoints.metrics.address=:8082"
image:
  name: traefik
  tag: 2.2.8
  pullPolicy: IfNotPresent
deployment:
  replicas: 3
  podAnnotations: 
    prometheus.io/port: '8082'
    prometheus.io/scrape: 'true'
resources:
  requests:
    memory: "500Mi"
    cpu: "100m"
  limits:
    memory: "3Gi"
    cpu: "500m"
autoscaling:
  enabled: true
   minReplicas: 3
   maxReplicas: 8
   metrics:
   - type: Resource
     resource:
       name: cpu
       targetAverageUtilization: 60
   - type: Resource
     resource:
       name: memory
       targetAverageUtilization: 60
service:
  spec:
    loadBalancerIP: "Your static ip in cloud provider"
    
